<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

# **Hands-on Lab: Interactive Visual Analytics with Folium**

Estimated time needed: **40** minutes

The launch success rate may depend on many factors such as payload mass, orbit type, and so on. It may also depend on the location and proximities of a launch site, i.e., the initial position of rocket trajectories. Finding an optimal location for building a launch site certainly involves many factors and hopefully we could discover some of the factors by analyzing the existing launch site locations.

In the previous exploratory data analysis, we have visualized the SpaceX launch dataset using `matplotlib` and `seaborn` and discovered some preliminary correlations between the launch site and success rates. Now, we will be performing more interactive visual analytics using `Folium`.

## Objectives

This project phase contains the following steps:

*   **TASK 1:** Mark all launch sites on a map
*   **TASK 2:** Mark the success/failed launches for each site on the map
*   **TASK 3:** Calculate the distances between a launch site to its proximities

After completing the above steps, we should be able to find some geographical patterns about launch sites.

Let's first import required Python packages for this lab:

In [16]:
# Installing needed libraries - Use this when running in the browser

#import piplite
#await piplite.install(['folium'])
#await piplite.install(['pandas'])

In [17]:
# Importing required libraries

import folium
import pandas as pd

In [18]:
# Importing folium MarkerCluster plugin, MousePosition plugin, and folium DivIcon plugin

from folium.plugins import MarkerCluster
from folium.plugins import MousePosition
from folium.features import DivIcon

If you need to refresh your memory about folium, you may download and refer to this previous folium lab:

[Generating Maps with Python](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/labs/v4/DV0101EN-Exercise-Generating-Maps-in-Python.ipynb)

First, let's try to add each site's location on a map using site's latitude and longitude coordinates

The following dataset with the name `spacex_launch_geo.csv` is an augmented dataset with latitude and longitude added for each site.

In [19]:
# Downloading and reading the `spacex_launch_geo.csv`

#from js import fetch
import io

URL = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv'

# The commented out lines are needed if running in the browser
#resp = await fetch(URL)
#spacex_csv_file = io.BytesIO((await resp.arrayBuffer()).to_py())
#spacex_df = pd.read_csv(spacex_csv_file)

spacex_df = pd.read_csv(URL)

In [20]:
# Saving dataset locally

#spacex_df.to_csv('data/spacex_launch_geo.csv')

Now, we can take a look at the coordinates for each site.

In [21]:
# Selecting relevant columns: `Launch Site`, `Lat(Latitude)`, `Long(Longitude)`, `class`

spacex_df = spacex_df[['Launch Site', 'Lat', 'Long', 'class']]
launch_sites_df = spacex_df.groupby(['Launch Site'], as_index=False).first()
launch_sites_df = launch_sites_df[['Launch Site', 'Lat', 'Long']]
launch_sites_df

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610745

Above coordinates are just plain numbers that can not give us any intuitive insights about where those launch sites are. If we are good at geography, we can interpret those numbers directly in our minds. If not, that's fine too. Let's visualize those locations by pinning them on a map.

We first need to create a folium `Map` object, with an initial center location to be NASA Johnson Space Center at Houston, Texas.

In [22]:
# Map's start location is NASA Johnson Space Center

nasa_coordinates = [29.559684888503615, -95.0830971930759]
site_map = folium.Map(location=nasa_coordinates, zoom_start=10)

We could use `folium.Circle` to add a highlighted circle area with a text label on a specific coordinate. For example:

In [23]:
# Creating a blue circle at NASA Johnson Space Center's coordinates with a popup label showing its name

circle = folium.Circle(nasa_coordinates, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('NASA Johnson Space Center'))

# Creating a blue circle at NASA Johnson Space Center's coordinates with an icon showing its name
marker = folium.map.Marker(
    nasa_coordinates,
    # Creating an icon as a text label
    icon = DivIcon(
        icon_size = (20,20),
        icon_anchor = (0,0),
        html = '<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'NASA JSC',
        )
    )
site_map.add_child(circle)
site_map.add_child(marker)

And now we should find a small yellow circle near the city of Houston and we can zoom-in to see a larger circle.

Now, let's add a circle for each launch site in data frame `launch_sites`

*TODO:*  Create and add `folium.Circle` and `folium.Marker` for each launch site on the site map

An example of folium.Circle:

`folium.Circle(coordinate, radius=1000, color='#000000', fill=True).add_child(folium.Popup(...))`

An example of folium.Marker:

`folium.map.Marker(coordinate, icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'label', ))`

In [24]:
# Showing the location of the launch sites

# Initializing the map
site_map = folium.Map(location=nasa_coordinates, zoom_start=5)

# For each launch site, adding a Circle object based on its coordinates (Lat, Long) values. In addition, adding the Launch site name as a popup label
for launch_site, lat, long in zip(launch_sites_df['Launch Site'], launch_sites_df.Lat, launch_sites_df.Long):
    # Creating circle based on the coordinates
    circle = folium.Circle([lat, long], radius=1000, color='#000000', fill=True).add_child(folium.Popup(launch_site))
    # Adding circle to map    
    site_map.add_child(circle)

    # Creating marker
    marker = folium.map.Marker(
        [lat, long],
        # Creating an icon as a text label
        icon = DivIcon(
            icon_size = (20,20),
            icon_anchor = (0,0),
            html = '<div style="font-size: 12; color:#d35400;"><b>' + launch_site + '</b></div>',
            )
        )
    # Adding marker to map
    site_map.add_child(marker)

site_map

The generated map with marked launch sites should look similar to the following:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_markers.png">
</center>

Now, we can explore the map by zooming-in/out the marked areas.

Try to answer the following questions:

*   Are all launch sites in proximity to the Equator line?
*   Are all launch sites in very close proximity to the coast?

Also please try to explain your findings.

**Answers**

* No, all launch sites are not close to the equator line. They are 28 and 34 degrees north of the equator.
* Yes, all four launch sites are close to the coast line.

In [ ]:
# Task 2: Marking the success/failed launches for each site on the map

Next, let's try to enhance the map by adding the launch outcomes for each site, and see which sites have high success rates.
Recall that data frame spacex_df has detailed launch records, and the `class` column indicates if this launch was successful or not

In [25]:
# Showing a few records from the SpaceX dataset

spacex_df.tail(10)

     Launch Site        Lat       Long  class
46    KSC LC-39A  28.573255 -80.646895      1
47    KSC LC-39A  28.573255 -80.646895      1
48    KSC LC-39A  28.573255 -80.646895      1
49  CCAFS SLC-40  28.563197 -80.576820      1
50  CCAFS SLC-40  28.563197 -80.576820      1
51  CCAFS SLC-40  28.563197 -80.576820      0
52  CCAFS SLC-40  28.563197 -80.576820      0
53  CCAFS SLC-40  28.563197 -80.576820      0
54  CCAFS SLC-40  28.563197 -80.576820      1
55  CCAFS SLC-40  28.563197 -80.576820      0

Next, let's create markers for all launch records.
If a launch was successful `(class=1)`, then we use a green marker and if a launch was failed, we use a red marker `(class=0)`

Note that a launch only happens in one of the four launch sites, which means many launch records will have the exact same coordinates. Marker clusters can be a good way to simplify a map containing of many markers having the same coordinates.

Let's first create a `MarkerCluster` object.

In [26]:
# Creating a marker cluster

marker_cluster = MarkerCluster()

*TODO:* Create a new column in `spacex_df` dataframe called `marker_color` to store the marker colors based on the `class` value

In [27]:
# Creating a new column in the dataframe to store the color of the marker

spacex_df['marker_color'] = spacex_df['class'].apply(lambda x: 'red' if x == 0 else 'green')

*TODO:* For each launch result in `spacex_df` data frame, add a `folium.Marker` to `marker_cluster`

In [28]:
# Adding a marker to the marker cluster for each launch result

# Adding marker_cluster (created previously) to current site_map
site_map.add_child(marker_cluster)

for index, record in spacex_df.iterrows():
    # TODO: Create and add a Marker cluster to the site map
    # marker = folium.Marker(...)

    # Creating marker
    marker = folium.map.Marker(
        [record['Lat'], record['Long']],
        # Creating an icon as a text label
        icon = folium.Icon(color='white', icon_color=record['marker_color'])
        )    
    # Adding marker to marker cluster
    marker_cluster.add_child(marker)

site_map

Your updated map may look like the following screenshots:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_cluster.png">
</center>

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_cluster_zoomed.png">
</center>

From the color-labeled markers in marker clusters, we can easily identify which launch sites have relatively high success rates.

In [ ]:
# TASK 3: Calculate the distances between a launch site to its proximities

Next, we need to explore and analyze the proximities of launch sites.

Let's first add a `MousePosition` on the map to get the coordinates for a mouse over a point on the map. As such, while we are exploring the map, we can easily find the coordinates of any points of interests (such as railways)

In [29]:
# Adding Mouse Position to get the coordinates (Lat, Long) for a mouse over on the map

formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)

site_map.add_child(mouse_position)
site_map

Now zoom in to a launch site and explore its proximity to see if you can easily find any railway, highway, coastline, etc. Move your mouse to these points and mark down their coordinates (shown on the top-right) in order to the distance to the launch site.

Now zoom in to a launch site and explore its proximity to see if you can easily find any railway, highway, coastline, etc. Move your mouse to these points and mark down their coordinates (shown on the top-left) in order to the distance to the launch site.

In [30]:
# Creating a function to calculate the distance between two points on the map

from math import sin, cos, sqrt, atan2, radians

def calculate_distance(lat1, lon1, lat2, lon2):
    # approximate radius of earth in km
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

*TODO:* Mark down a point on the closest coastline using MousePosition and calculate the distance between the coastline point and the launch site.

In [31]:
# Finding coordinates of the closest coastline

# Getting the coordinates for launch site: CCAFS SLC-40
launch_site_coordinates = spacex_df[spacex_df['Launch Site'] == 'CCAFS SLC-40'][['Lat', 'Long']].iloc[0].to_list()
launch_site_lat = launch_site_coordinates[0]
launch_site_lon = launch_site_coordinates[1]

# Latitude and longitude of coast point
coastline_lat = 28.56329
coastline_lon = -80.568

# Calculate distance in km
distance_coastline = round(calculate_distance(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon), 2)

In [32]:
# Creating and adding a folium.Marker on the selected closest coastline point on the map
# Displaying the distance between coastline point and launch site using the icon property 

distance_marker = folium.Marker(
    [coastline_lat, coastline_lon],
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 14; color:#d35400;"><b>%s</b></div>' % "{:10.2f} KM".format(distance_coastline),
        )
    )

site_map.add_child(distance_marker)
site_map

*TODO:* Draw a `PolyLine` between a launch site to the selected coastline point

In [33]:
# Creating a `folium.PolyLine` object using the coastline coordinates and launch site coordinates

coordinates = [
    [launch_site_lat, launch_site_lon],      # Point A (Launch Site)
    [coastline_lat, coastline_lon]           # Point B (Coastline)
]
line = folium.PolyLine(locations=coordinates, weight=1)
site_map.add_child(line)
site_map

The updated map with the distance line should look like the following screenshot:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_distance.png">
</center>

*TODO:* Similarly, you can draw a line betwee a launch site to its closest city, railway, highway, etc. You need to use `MousePosition` to find the their coordinates on the map first

A railway map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/railway.png">
</center>

A highway map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/highway.png">
</center>

A city map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/city.png">
</center>

In [34]:
# Creating a marker with distance to the closest city, railway, and highway. And drawing a line between the marker to the launch site

location_coordinates = [
    [28.08148, -80.61104],     # City
    [28.58212, -80.65434],     # Railway
    [28.56413, -80.57090]      # Highway
]

location_distances = []
for location in location_coordinates:
    # Calculating the distance between the location and the launch site
    location_lat = location[0]
    location_lon = location[1]
    location_distance = round(calculate_distance(launch_site_lat, launch_site_lon, location_lat, location_lon), 2)
    location_distances.append(location_distance)

    # Creating the marker for the location
    location_marker = folium.Marker(
        [location_lat, location_lon],
        icon=DivIcon(
            icon_size=(20,20),
            icon_anchor=(0,0),
            html='<div style="font-size: 14; color:#d35400;"><b>%s</b></div>' % "{:10.2f} KM".format(location_distance),
            )
        )

    # Adding marker to map
    site_map.add_child(location_marker)

    # Adding line to map
    line = folium.PolyLine(locations=[[launch_site_lat, launch_site_lon], [location_lat, location_lon]], weight=1)
    site_map.add_child(line)

site_map

After you plot distance lines to the proximities, you can answer the following questions easily:

*   Are launch sites in close proximity to railways?
*   Are launch sites in close proximity to highways?
*   Are launch sites in close proximity to coastline?
*   Do launch sites keep certain distance away from cities?

Also please try to explain your findings.

**Answer**

* The launch sites are relatively close to railways.
* Yes, they are close to highways.
* Yes, launch sites are very close to the coastline.
* Yes, launch sites do keep some distance from cities.

# Next Steps:

Now you have discovered many interesting insights related to the launch sites' location using folium, in a very interactive way. Next, you will need to build a dashboard using Ploty Dash on detailed launch records.

## Authors

[Pratiksha Verma](https://www.linkedin.com/in/pratiksha-verma-6487561b1/)

<!--## Change Log--!>

<!--| Date (YYYY-MM-DD) | Version | Changed By      | Change Description      |
| ----------------- | ------- | -------------   | ----------------------- |
| 2022-11-09        | 1.0     | Pratiksha Verma | Converted initial version to Jupyterlite|--!>

### <h3 align="center"> IBM Corporation 2022. All rights reserved. <h3/>